"""add appointment status

Revision ID: 0d17c7b44592
Revises: e8f10ec4d130
Create Date: 2026-09-02 18:16:23.342197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d17c7b44592'
down_revision: Union[str, Sequence[str], None] = 'e8f10ec4d130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'status')
    # ### end Alembic commands ###
