"""add patient id to users

Revision ID: e39544f5fcac
Revises: ff5bd03092c2
Create Date: 2026-08-29 20:20:45.779795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39544f5fcac'
down_revision: Union[str, Sequence[str], None] = 'ff5bd03092c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patient_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'patient_id')
    # ### end Alembic commands ###
