"""add audit timestamp

Revision ID: e8f10ec4d130
Revises: fab49e2e3fab
Create Date: 2026-09-01 22:58:26.054673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f10ec4d130'
down_revision: Union[str, Sequence[str], None] = 'fab49e2e3fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'timestamp')
    # ### end Alembic commands ###
